name: Update Coding Stats

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install PyGithub

      - name: Generate SVG
        run: python generate_stats_svg.py
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add coding_stats.svg
          git commit -m "Update coding stats" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Alaire1/stats.git HEAD:main

